language: node_js
node_js:
  - "node"

install:
  - if [[ $TRAVIS_BRANCH =~ (^feature) ]]; then sed -i '6s/web/web_dev/' package.json; fi;
  - TZ=Europe/Warsaw
  - current_date_time="`date`"
  - sed -i 's/NO_DEPLOY_DATE/'"$current_date_time"'/' ./src/static/json/GlobalConfig.json
  - sed -i 's~NO_DEPLOY_BRANCH~'"$TRAVIS_BRANCH"'~' ./src/static/json/GlobalConfig.json
  - sed -i 's/NO_DEPLOY_COMMIT/'"${TRAVIS_COMMIT:0:7}"'/' ./src/static/json/GlobalConfig.json
  - npm install
script:
  - npm run build


deploy:
  #deploy to libamtrack.github.io/web
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN # defined at Travis/Settings/Environment Variables
    keep-history: true
    local-dir: ./dist
    on:
      branch: master

  #deploy to libamtrack.github.io/web_dev
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN # defined at Travis/Settings/Environment Variables
    keep-history: true
    local-dir: ./dist
    repo: libamtrack/web_dev
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^feature #deploy when commit to branch feature
